# Inventário de TESTE gerado automaticamente pelo Terraform — não editar

[todas_as_vms]
    SW1 ansible_host=192.168.10.106 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:29:3c:61 mac_net1=fa:16:3e:c6:05:ab mac_net2=fa:16:3e:9c:c4:89 mac_net3=fa:16:3e:18:23:5b mac_net4=fa:16:3e:ce:fd:7e mac_net5=fa:16:3e:c5:1f:b9 mac_net6=fa:16:3e:18:8f:1f mac_net7=fa:16:3e:4c:c2:cb mac_net8=fa:16:3e:8c:9f:4e
    SW2 ansible_host=192.168.10.197 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:2f:dc:77 mac_net1=fa:16:3e:8e:fb:eb mac_net2=fa:16:3e:d2:05:27 mac_net3=fa:16:3e:9a:76:7a mac_net4=fa:16:3e:d3:a2:7d mac_net5=fa:16:3e:5f:0d:90 mac_net6=fa:16:3e:42:06:2d mac_net7=fa:16:3e:85:ea:5c
    VM1 ansible_host=192.168.10.188 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:e0:5f:66 mac_net1=fa:16:3e:93:ed:01
    VM11 ansible_host=192.168.10.139 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:a1:21:7b mac_net1=fa:16:3e:57:ac:f2 mac_net2=fa:16:3e:9f:3a:76
    VM2 ansible_host=192.168.10.112 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:6f:b6:ed mac_net1=fa:16:3e:1e:c4:c8
    VM3 ansible_host=192.168.10.102 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:87:44:16 mac_net1=fa:16:3e:53:a9:c1
    VM4 ansible_host=192.168.10.118 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:5e:b4:61 mac_net1=fa:16:3e:b5:b2:9c mac_net2=fa:16:3e:cc:7b:9e mac_net3=fa:16:3e:f9:ed:44
    VM6 ansible_host=192.168.10.141 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:13:dc:a0 mac_net1=fa:16:3e:87:ec:3c
    VM7 ansible_host=192.168.10.142 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:94:da:fc mac_net1=fa:16:3e:98:ec:40
    VM9 ansible_host=192.168.10.150 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:fe:44:03 mac_net1=fa:16:3e:bc:89:10
    VM_DEV ansible_host=192.168.10.191 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:da:e8:4d mac_net1=fa:16:3e:b2:15:62
    VM_USER1 ansible_host=192.168.10.116 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:c3:ec:8e mac_net1=fa:16:3e:6f:78:3e
    VM_USER2 ansible_host=192.168.10.160 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:d5:81:09 mac_net1=fa:16:3e:bd:f7:6d

[SW1]
        SW1 ansible_host=192.168.10.106 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:29:3c:61 mac_net1=fa:16:3e:c6:05:ab mac_net2=fa:16:3e:9c:c4:89 mac_net3=fa:16:3e:18:23:5b mac_net4=fa:16:3e:ce:fd:7e mac_net5=fa:16:3e:c5:1f:b9 mac_net6=fa:16:3e:18:8f:1f mac_net7=fa:16:3e:4c:c2:cb mac_net8=fa:16:3e:8c:9f:4e
                                                                                                    
[SW2]
                SW2 ansible_host=192.168.10.197 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:2f:dc:77 mac_net1=fa:16:3e:8e:fb:eb mac_net2=fa:16:3e:d2:05:27 mac_net3=fa:16:3e:9a:76:7a mac_net4=fa:16:3e:d3:a2:7d mac_net5=fa:16:3e:5f:0d:90 mac_net6=fa:16:3e:42:06:2d mac_net7=fa:16:3e:85:ea:5c
                                                                                            
[VM1]
                        VM1 ansible_host=192.168.10.188 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:e0:5f:66 mac_net1=fa:16:3e:93:ed:01
                                                                                    
[VM2]
                                        VM2 ansible_host=192.168.10.112 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:6f:b6:ed mac_net1=fa:16:3e:1e:c4:c8
                                                                    
[VM3]
                                                VM3 ansible_host=192.168.10.102 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:87:44:16 mac_net1=fa:16:3e:53:a9:c1
                                                            
[VM4]
                                                        VM4 ansible_host=192.168.10.118 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:5e:b4:61 mac_net1=fa:16:3e:b5:b2:9c mac_net2=fa:16:3e:cc:7b:9e mac_net3=fa:16:3e:f9:ed:44
                                                    
[VM6]
                                                                VM6 ansible_host=192.168.10.141 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:13:dc:a0 mac_net1=fa:16:3e:87:ec:3c
                                            
[VM7]
                                                                        VM7 ansible_host=192.168.10.142 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:94:da:fc mac_net1=fa:16:3e:98:ec:40
                                    
[VM9]
                                                                                VM9 ansible_host=192.168.10.150 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:fe:44:03 mac_net1=fa:16:3e:bc:89:10
                            
[VM11]
                                VM11 ansible_host=192.168.10.139 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:a1:21:7b mac_net1=fa:16:3e:57:ac:f2 mac_net2=fa:16:3e:9f:3a:76
                                                                            
[VM_DEV]
                                                                                        VM_DEV ansible_host=192.168.10.191 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:da:e8:4d mac_net1=fa:16:3e:b2:15:62
                    
[VM_USER1]
                                                                                                VM_USER1 ansible_host=192.168.10.116 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:c3:ec:8e mac_net1=fa:16:3e:6f:78:3e
            
[VM_USER2]
                                                                                                        VM_USER2 ansible_host=192.168.10.160 ansible_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/labredes_key mac_net0=fa:16:3e:d5:81:09 mac_net1=fa:16:3e:bd:f7:6d
    
[switches:children]
SW1
SW2
